server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    show_sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        #변수 명과 DB칼럼명을 그대로 매핑
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl